### ISSUE TITLE
This application needs a Netlify host

### ISSUE THREAD

**Issue by anirudh-0** [Shemicalx/typography-tester#1]
Hello,
As you know, Netlify offers hosting and this app deserves to be hosted and maintained as progress is made upon it.
I believe netlify hosts stuff for free and it could a be fun thing to do.

-- Andaei

**Comment by Shemicalx** [comment]
Hi Andaei! 
Great idea. Hosted the app and added a description the explain how it should be used. Thanks for the feedback! 
Go check it out and tell me what you think ;)

**Comment by anirudh-0** [comment]
I am not lying when I tell you this, it looks amazing. But more than its looks, I am honestly surprised by how many useful features got added to this. So very proud. <3

**Comment by anirudh-0** [comment]
I do have an input regarding the latest changes, it seems like you replaced env variable with the actual api key, possibly for sake of deployment to netlify. I have to say the previous implementation is safer and you can provide the environment variables to your netlify deploy in other ways.

**Comment by Shemicalx** [comment]
Thank you so much Andaei! This help's me so much. 
As for the env variable - it was a temporary solution indeed, but thanks to you I got motivated to learn how to use env variables on Netlify. Thanks once again! I believe it is better now <3
